fastcgi_pass              php${INSTANCE}:9000;
fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
fastcgi_param HTTPS       ${FASTCGI_HTTPS};
include fastcgi_params;
fastcgi_buffer_size       128k;
fastcgi_buffers           4 256k;
fastcgi_busy_buffers_size 256k;
fastcgi_connect_timeout   60s;
fastcgi_send_timeout      120s;
fastcgi_read_timeout      120s;
